[project]
name = "vae-sfa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "equinox>=0.13.2",
    "h5py>=3.15.1",
    "jax>=0.8.0",
    "pillow>=12.0.0",
]
